import { Venue, Artist, Event } from "./types";

export const mockVenues: Venue[] = [
  {
    id: "v1",
    city_slug: "nyc",
    name: "Blue Note",
    slug: "blue-note",
    address: "131 W 3rd St, New York, NY 10012",
    neighborhood: "Greenwich Village",
    region: "manhattan",
    lat: 40.7308,
    lng: -74.0005,
    website: "https://www.bluenotejazz.com",
    sponsor_tier: "marquee",
  },
  {
    id: "v2",
    city_slug: "nyc",
    name: "Village Vanguard",
    slug: "village-vanguard",
    address: "178 7th Ave S, New York, NY 10014",
    neighborhood: "Greenwich Village",
    region: "manhattan",
    lat: 40.7359,
    lng: -74.0019,
    website: "https://villagevanguard.com",
    sponsor_tier: "marquee",
  },
  {
    id: "v3",
    city_slug: "nyc",
    name: "Smalls Jazz Club",
    slug: "smalls-jazz-club",
    address: "183 W 10th St, New York, NY 10014",
    neighborhood: "Greenwich Village",
    region: "manhattan",
    lat: 40.7339,
    lng: -74.0027,
    website: "https://www.smallslive.com",
    sponsor_tier: "spotlight",
  },
  {
    id: "v4",
    city_slug: "nyc",
    name: "Dizzy's Club",
    slug: "dizzys-club",
    address: "10 Columbus Cir, New York, NY 10019",
    neighborhood: "Midtown West",
    region: "manhattan",
    lat: 40.7688,
    lng: -73.9831,
    website: "https://jazz.org/dizzys",
    sponsor_tier: "spotlight",
  },
  {
    id: "v5",
    city_slug: "nyc",
    name: "Smoke Jazz & Supper Club",
    slug: "smoke-jazz",
    address: "2751 Broadway, New York, NY 10025",
    neighborhood: "Upper West Side",
    region: "manhattan",
    lat: 40.8008,
    lng: -73.9681,
    website: "https://www.smokejazz.com",
    sponsor_tier: "free",
  },
  {
    id: "v6",
    city_slug: "nyc",
    name: "Bar Bayeux",
    slug: "bar-bayeux",
    address: "1066 Nostrand Ave, Brooklyn, NY 11225",
    neighborhood: "Crown Heights",
    region: "brooklyn",
    lat: 40.6597,
    lng: -73.9509,
    website: "https://www.barbayeux.com",
    sponsor_tier: "free",
  },
  {
    id: "v7",
    city_slug: "nyc",
    name: "Mezzrow",
    slug: "mezzrow",
    address: "163 W 10th St, New York, NY 10014",
    neighborhood: "Greenwich Village",
    region: "manhattan",
    lat: 40.7341,
    lng: -74.0021,
    website: "https://www.mezzrow.com",
    sponsor_tier: "free",
  },
  {
    id: "v8",
    city_slug: "nyc",
    name: "Cellar Dog",
    slug: "cellar-dog",
    address: "75 Christopher St, New York, NY 10014",
    neighborhood: "West Village",
    region: "manhattan",
    lat: 40.7334,
    lng: -74.0033,
    sponsor_tier: "free",
  },
];

export const mockArtists: Artist[] = [
  { id: "a1", name: "Marcus Strickland", slug: "marcus-strickland" },
  { id: "a2", name: "Samara Joy", slug: "samara-joy" },
  { id: "a3", name: "Ambrose Akinmusire", slug: "ambrose-akinmusire" },
  { id: "a4", name: "Cecile McLorin Salvant", slug: "cecile-mclorin-salvant" },
  { id: "a5", name: "Brad Mehldau Trio", slug: "brad-mehldau-trio" },
  { id: "a6", name: "Lakecia Benjamin", slug: "lakecia-benjamin" },
  { id: "a7", name: "Joel Ross", slug: "joel-ross" },
  { id: "a8", name: "Immanuel Wilkins", slug: "immanuel-wilkins" },
  { id: "a9", name: "Marquis Hill", slug: "marquis-hill" },
  { id: "a10", name: "Connie Han Trio", slug: "connie-han-trio" },
  { id: "a11", name: "Mike Stern Band", slug: "mike-stern-band" },
  { id: "a12", name: "The Baylor Project", slug: "the-baylor-project" },
];

// Helper to generate dates relative to "today"
function getDateString(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split("T")[0];
}

export const mockEvents: Event[] = [
  // Tonight
  {
    id: "e1",
    venue_id: "v1",
    venue: mockVenues[0],
    artist_id: "a5",
    artist: mockArtists[4],
    date: getDateString(0),
    start_time: "20:00",
    end_time: "23:00",
    is_boosted: false,
  },
  {
    id: "e2",
    venue_id: "v1",
    venue: mockVenues[0],
    artist_id: "a5",
    artist: mockArtists[4],
    date: getDateString(0),
    start_time: "23:30",
    is_boosted: false,
  },
  {
    id: "e3",
    venue_id: "v2",
    venue: mockVenues[1],
    artist_id: "a8",
    artist: mockArtists[7],
    date: getDateString(0),
    start_time: "21:00",
    end_time: "23:30",
    is_boosted: false,
  },
  {
    id: "e4",
    venue_id: "v3",
    venue: mockVenues[2],
    artist_id: "a7",
    artist: mockArtists[6],
    date: getDateString(0),
    start_time: "19:30",
    end_time: "22:00",
    is_boosted: false,
  },
  {
    id: "e5",
    venue_id: "v3",
    venue: mockVenues[2],
    artist_id: "a1",
    artist: mockArtists[0],
    date: getDateString(0),
    start_time: "22:30",
    is_boosted: false,
  },
  {
    id: "e6",
    venue_id: "v4",
    venue: mockVenues[3],
    artist_id: "a2",
    artist: mockArtists[1],
    date: getDateString(0),
    start_time: "19:30",
    end_time: "21:30",
    is_boosted: true,
  },
  {
    id: "e7",
    venue_id: "v5",
    venue: mockVenues[4],
    artist_id: "a6",
    artist: mockArtists[5],
    date: getDateString(0),
    start_time: "20:00",
    end_time: "23:00",
    is_boosted: false,
  },
  {
    id: "e8",
    venue_id: "v6",
    venue: mockVenues[5],
    artist_id: "a9",
    artist: mockArtists[8],
    date: getDateString(0),
    start_time: "21:00",
    end_time: "00:00",
    is_boosted: false,
  },
  {
    id: "e9",
    venue_id: "v7",
    venue: mockVenues[6],
    artist_id: "a10",
    artist: mockArtists[9],
    date: getDateString(0),
    start_time: "19:00",
    end_time: "22:00",
    is_boosted: false,
  },
  {
    id: "e10",
    venue_id: "v8",
    venue: mockVenues[7],
    artist_id: "a11",
    artist: mockArtists[10],
    date: getDateString(0),
    start_time: "20:30",
    end_time: "23:30",
    is_boosted: false,
  },
  // Tomorrow
  {
    id: "e11",
    venue_id: "v1",
    venue: mockVenues[0],
    artist_id: "a4",
    artist: mockArtists[3],
    date: getDateString(1),
    start_time: "20:00",
    end_time: "23:00",
    is_boosted: true,
  },
  {
    id: "e12",
    venue_id: "v2",
    venue: mockVenues[1],
    artist_id: "a3",
    artist: mockArtists[2],
    date: getDateString(1),
    start_time: "21:00",
    end_time: "23:30",
    is_boosted: false,
  },
  {
    id: "e13",
    venue_id: "v4",
    venue: mockVenues[3],
    artist_id: "a12",
    artist: mockArtists[11],
    date: getDateString(1),
    start_time: "19:30",
    end_time: "21:30",
    is_boosted: false,
  },
  {
    id: "e14",
    venue_id: "v6",
    venue: mockVenues[5],
    artist_id: "a1",
    artist: mockArtists[0],
    date: getDateString(1),
    start_time: "21:00",
    end_time: "00:00",
    is_boosted: false,
  },
];
